# k8s\secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: todo-secrets
type: Opaque
stringData:
  # Yahan apni actual values likhein
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "mysecretpassword"
  POSTGRES_DB: "todo_db"
  # DATABASE_URL: postgresql://<user>:<password>@<service-name>:5432/<db-name>
  DATABASE_URL: postgresql://neondb_owner:npg_DRmg9fK7ZYrk@ep-sweet-frog-a1hrxlm4-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
  # Apni OpenAI Key neeche paste karein (bina quotes ke bhi chalega)
  OPENAI_API_KEY: "replace-with-your-real-key-before-deploying"